Nuevo propiertes:
#--- NUEVO PROPERTIS ---#
spring.application.name=Concesionaria

# BASE DE DATOS SUPABASE
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.iikvsptmtkgtvqxcocba
# Ac� pusimos un comod�n para que la contrase�a no quede en GitHub:
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=America/Argentina/Buenos_Aires

server.port=${PORT:8080}

#--- MULTIPART (Upload de archivos/videos) ---
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

#--- JWT ---
jwt.secret=${JWT_SECRET:QmVycnlDcnlwdG9LZXlNb3JlVGhhblR3ZW50eVNpeEJ5dGVzMjU2Qml0cw}
jwt.expiration.ms=86400000

#--- SMTP ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mycarautos.mdp@gmail.com
# Otra contrase�a oculta:
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.transport.protocol=smtp
spring.mail.debug=true

spring.scheduling.timezone=America/Argentina/Buenos_Aires

# --- URLs Y TOKENS ---
# Render va a inyectar estos comodines, tu compu no.
mercadopago.access-token.private=${MP_TOKEN_PRIVATE}
mercadopago.access-token.public=${MP_TOKEN_PUBLIC}
frontend.url=${FRONTEND_URL:http://localhost:4200/}
backend.base-url=${BACKEND_URL:http://localhost:8080/}

#--- CLOUDINARY ---
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

#--- Google OAuth2 Configuration ---
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:dummy-google-client-id}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:dummy-google-client-secret}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
# Fijate c�mo ac� tambi�n usamos el comod�n de la URL para que sea din�mico:
spring.security.oauth2.client.registration.google.redirect-uri=${BACKEND_URL:http://localhost:8080}/login/oauth2/code/google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v2/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=email

#--- DEBUG JWT ---
logging.level.concesionaria.example.Concesionaria.config.JwtAuthenticationFilter=DEBUG