spring.application.name=Concesionaria

spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.iikvsptmtkgtvqxcocba
spring.datasource.password=nahuel123!"
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=America/Argentina/Buenos_Aires

server.port=${PORT:8080}

#--- MULTIPART (Upload de archivos/videos) ---
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

#--- JWT ---
jwt.secret=QmVycnlDcnlwdG9LZXlNb3JlVGhhblR3ZW50eVNpeEJ5dGVzMjU2Qml0cw
# 86400000 ms = 24 horas
jwt.expiration.ms=86400000

#--- SMTP ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mycarautos.mdp@gmail.com
spring.mail.password=ccpz gmkt eblu ztyo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.transport.protocol=smtp
spring.mail.debug=true

# Configuración de Zona Horaria para tareas programadas
spring.scheduling.timezone=America/Argentina/Buenos_Aires

# Configuración SDK Mercado Pago
mercadopago.access-token.private=APP_USR-1904624528493601-111318-fe844dc9cd0eb82db1b338edb1fb6706-2989162574
mercadopago.access-token.public=APP_USR-b7c51155-9c00-4bbf-b39f-78195c900a4a
frontend.url=http://localhost:4200/
backend.base-url=http://localhost:8080/

#--- CLOUDINARY ---
cloudinary.cloud-name=dx5tea2qx
cloudinary.api-key=273383971269598
cloudinary.api-secret=Jq34Awhl4EQRvm88z1zChALS84M

#--- Google OAuth2 Configuration ---
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:dummy-google-client-id}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:dummy-google-client-secret}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

#--- Provider Configuration ---
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v2/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=email

#--- DEBUG JWT ---
logging.level.concesionaria.example.Concesionaria.config.JwtAuthenticationFilter=DEBUG